### ISSUE TITLE
Documents to fetch from yoda

### ISSUE THREAD

**Issue by jsheunis** [guts-consortium/guts-explorer#5]
- overview, XLSX, (infrequent)
- file-level metadata, JSON, (frequent)
- participant-level metadata, CSV, (frequent)

**Comment by jsheunis** [comment]
@muldersf can you make sure that these filenames are always consistent? At the moment the filenames are updated whenever there is a new version, but this is a problem for any service that needs to fetch these files at some defined interval. It would be best if the new versions just replace the old versions, and the filename stays constant.

**Comment by muldersf** [comment]
Hi @jsheunis, I'll update the scripts to ensure that filenames consistently adhere to the following format:

- guts-measure-overview.xlsx
- guts-file-level-metadata.json
- guts-ppn-level-metadata.json

**Comment by jsheunis** [comment]
This process has been updated such that 

> - guts-measure-overview.json
> - guts-file-level-metadata.json
> - guts-subject-level-metadata.json

are all made available through the neptune metadata server/api
