### ISSUE TITLE
Details to record in basket checkout form

### ISSUE THREAD

**Issue by jsheunis** [guts-consortium/guts-explorer#7]
The current basket checkout form only asks for the name:

<img width="489" alt="Screenshot 2024-03-29 at 15 52 36" src="https://github.com/guts-consortium/guts-explorer/assets/10141237/6e11753b-c150-4cbd-8f9b-73bc83ec56a4">

We need to decide:
- what text to include in this form,
- which specific fields need to be collected
- which instructions to give to the user

**Comment by eduardklap** [comment]
For the first version of the system, I think we can keep the text quite general.
Later when we have a procedure in place, we should describe it in more detail here.

**Suggestion for text** (assuming the info will be added to the metadata file):

_Please complete the following information to create a data request (currently only GUTS researchers can request data).
This information will be attached to the metadata file. Once you have downloaded the file, please send it via email to [datamanager@gutsproject.com?]. The GUTS Steering Committee will evaluate your request. Once approved, the data manager will make the data available to you via Yoda.
Note that in the future, we plan to include functionality to directly request data via this form._

**Suggestion for fields** (specific fields might depend on the 'data use policy' that we are planning to draft):
- Name (primary applicant)
- Affiliation
- Email address
- Name(s) additional team members / secondary applicants
- Project title
- Short project description (research questions)
- Usage period (?)
- Additional comments
- (future) checkbox that you are aware of and agree with data use policy

**Comment by jsheunis** [comment]
These have all been implemented and are available in the latest version in production
